name: Deploy web-react to GitHub Pages

on:
  push:
    branches: [main, master]
    paths:
      - "apps/web-react/**"
      - "packages/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - ".github/workflows/deploy-pages.yml"
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app for Pages
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

        # Build all libraries that apps import from dist
      - name: Build libraries
        run: pnpm build:libs

      # Extract and compile app catalogs so runtime imports exist (ESM .js/.mjs)
      - name: Extract app catalogs (web-react)
        run: pnpm -C apps/web-react lingui:extract

      - name: Compile app catalogs (web-react)
        run: pnpm -C apps/web-react lingui:compile

      # 🧪 (Optional but recommended) Typecheck the app explicitly
      - name: Typecheck web-react
        run: pnpm -C apps/web-react exec tsc --noEmit

      # Build the app with the correct base for GitHub Pages
      # VITE_BASE ensures assets resolve under /{repo}/ instead of /
      - name: Build web-react (GitHub Pages base)
        env:
          CI: true
          VITE_BASE: "/${{ github.event.repository.name }}/"
        run: pnpm -C apps/web-react build

      # Add SPA fallback so deep links work on Pages
      - name: Add SPA 404 fallback
        run: cp apps/web-react/dist/index.html apps/web-react/dist/404.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web-react/dist

  deploy:
    name: Deploy to Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
